version: "3"

services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      SPIGET_RESOURCES: 79320
      # https://qiita.com/STSynthe/items/28fa9edac587ec6e0414
      INIT_MEMORY: "1G"
      MAX_MEMORY: "2G"
      TZ: "Asia/Tokyo"
    tty: true
    stdin_open: true
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /opt/mcserver:/data
