version: "3"

services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: SPIGOT
      SPIGET_RESOURCES: 79320
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /opt/mcserver:/data
